### ISSUE TITLE
How to use the tool on the enabled MFA environment?

### ISSUE THREAD

**Issue by ninhhv** [mcafee-enterprise/mvision-edr-activity-feed#46]
When my org enforce enabled MFA for authen, so How to use this tool with those account?

**Comment by mohlcyber** [comment]
Hi Ninhhv, the activity feeds as well as the dxlstreamingclient libs got updated to use the new client id and client secret auth. This should solve your issue with enabled MFA for auth.

**Comment by msilvaca-trellix** [comment]
Closing this issue with Martin's explanation.
